FROM node: 18-alpine

WORKDIR /

COPY package*.json ./

RUN npm install

# TODO: Add up .env support 
# TODO: If you are building your code for production
# RUN npm ci --omit=dev

COPY . .

EXPOSE 3000
CMD [ "node", "index.js" ]