FROM node: 18-alpine

WORKDIR /usr/src/portalsapi

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

#TODO: write the command to run the application
#TODO: ADD environment variables
CMD [ "node", "index.js" ]